theme: jekyll-theme-minimal
title: Levi Pulford
description: portfolio
nav:
  - title: Home
    url: /
  - title: About Me
    url: /about.html
  - title: Resume
    url: /resume.html
  - title: Contact
    url: /contact.html
