theme: jekyll-theme-minimal
plugins:
  - jekyll-remote-theme
include:
  - assets/css/custom.css
title: Levi Pulford
description: Portfolio
nav:
  - title: Home
    url: /
  - title: About Me
    url: /about.html
  - title: Resume
    url: /resume.html
  - title: Contact
    url: /contact.html
